### ISSUE TITLE
Small mistake

### ISSUE THREAD

**Issue by HemanthJabalpuri** [divinebird/pacextractor#2]
Sir you missed #include <sys/stat.h> header in pacextractor.c
When I try to compile it in CPP-N-IDE android app in android.. it shows error without the #include <sys/stat.h> header

**Comment by divinebird** [comment]
This application created for parse files on PC. And in normal case sys/stat.h is part of other header.

**Comment by HemanthJabalpuri** [comment]
@divinebird 
Can you please update pacextractor.c so that we can able to extract it to a specified directory like in this fork https://github.com/superr/pacextractor

I think your repo is the only one to unpack .pac with c code right?

Thanks

**Comment by HemanthJabalpuri** [comment]
@divinebird

I have forked your repo and made changes to it at https://github.com/HemanthJabalpuri/pacextractor

Can you please have a look at that.
If you confirm those are correct, I will give PR to this repo.

Thanks
